[project]
name = "eodhd-py"
version = "0.1.0"
description = "Python Implementation for EODHD API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "pre-commit",
    "printf-log-formatter",
    "coverage",
    "pytest",
    "pytest-asyncio",
    "ruff",
    "pyright[nodejs]",
    "pytest-randomly",
    "pytest-mock",
]

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover',
    "if __name__ == '__main__':",
]

[tool.ruff]
line-length = 120
target-version = "py311"
lint.select = ["A", "ANN", "ASYNC", "B", "C", "D", "F", "C90", "C4", "T20", "PT", "PLE", "PLR", "PLW", "SIM", "RUF", "RET"]
lint.ignore = ["ANN401", "PLR1711", "D400", "D203", "D212", "D415", "D401"]
lint.fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "ASYNC", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PLE", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
lint.unfixable = []
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PLR2004"]

[tool.pyright]
pythonVersion = "3.13"
pythonPlatform = "Linux"
typeCheckingMode = "strict"
# Those are enabled with strict mode, but can be uncommented to enable them in other modes
# reportUnknownMemberType = "error"
# reportUnknownVariableType = "error"
# reportUnknownArgumentType = "error"
# reportUnknownParameterType = "error"

executionEnvironments = [
    { root = "tests", reportPrivateUsage = false }
]
